export default ImagePath = {
   bag : require('../assets/Images/bag.png') ,
   Barista: require('../assets/Images/Barista.jpeg') ,
   Biriyani_bohvze : require('../assets/Images/Biriyani_bohvze.jpeg'),
   BurgerKing  : require('../assets/Images/BurgerKing.png'),
   Cart  : require('../assets/Images/Cart.jpeg'),
   dominos : require('../assets/Images/dominos.png'),
   Favourites : require('../assets/Images/Favourites.jpeg'),
   genie : require('../assets/Images/genie.webp'),
   Grocery_main_1218 : require('../assets/Images/Grocery_main_1218.jpg'),
   InstamartOff : require('../assets/Images/InstamartOff.png'),
   Katani : require('../assets/Images/Katani.jpg'),
   LaPino : require('../assets/Images/LaPino.png'),
   light : require('../assets/Images/light.png'),
   location : require('../assets/Images/location.png'),
   McDonald : require('../assets/Images/McDonald.png'),
   off1 : require('../assets/Images/off1.png'),
   off2 : require('../assets/Images/off2.png'),
   off3 : require('../assets/Images/off3.png'),
   off4 : require('../assets/Images/off4.png'),
   offer : require('../assets/Images/offer.png'),
   one : require('../assets/Images/one.png'),
   PizzaHut : require('../assets/Images/PizzaHut.jpg'),
   Search : require('../assets/Images/Search.png'),
   SubWay : require('../assets/Images/SubWay.jpg'),
   Swiggy : require('../assets/Images/Swiggy.png'),
   thumbsUp : require('../assets/Images/thumbsUp.png'),
   TopPick1 : require('../assets/Images/TopPick1.jpeg'),
   TopPick2 : require('../assets/Images/TopPick2.jpeg'),
   TopPick3 : require('../assets/Images/TopPick3.jpeg'),
   TopPick4 : require('../assets/Images/TopPick4.jpeg'),
   TopPick5 : require('../assets/Images/TopPick5.jpg'),
   TopPick7 : require('../assets/Images/TopPick7.jpeg'),
   TopPick8 : require('../assets/Images/TopPick8.jpeg'),
   trend : require('../assets/Images/trend.png'),
   user : require('../assets/Images/BurgerKing.user'),
   wallclock : require('../assets/Images/wall-clock.png'), 
}